Repository demo-Bloodtrail/bloodtrail-be, pull requests merged in 2024-02, with the labels that each got.

#111 feature(#105)api수정 및 포스팅 컨트롤러 수정
  index.js
  src/controller/commentController.js
  src/controller/postController.js
  src/controller/reportController.js
  src/middleware/postMiddleware.js
  src/middleware/reportMiddleware.js
  src/router/postRouter.js
  src/router/reportRouter.js
  src/schema/comment.js
  src/schema/post.js
  src/schema/report.js
Labels: :bug: Bug, :sparkles: Feature

#112 feat(#109): Crew API 작성
  index.js
  src/config/responseStatus.js
  src/controller/crewController.js
  src/router/crewRouter.js
  src/schema/crew.js
Labels: :sparkles: Feature

#113 Feature/110
  index.js
  package-lock.json
  package.json
  src/config/socket.js
  src/controller/chatRoomController.js
  src/public/main.css
  src/router/chatRoomRouter.js
  src/schema/chat.js
  src/schema/chatRoom.js
  src/view/chat.ejs
  src/view/chatRoom.ejs
  src/view/error.ejs
  src/view/main.ejs
  swagger/swagger.js
  swagger/userSwagger.yaml
Labels: :sparkles: Feature

#115 feature(#110) : socketConnect import 수정
  index.js
Labels: :bug: Bug

#114 feature(#105) 복수 신고에 대한 예외처리 추가(reportMidlleware)
  src/middleware/reportMiddleware.js
Labels: :bug: Bug

#117 키워드를 이용한 검색 api
  index.js
  src/controller/postController.js
  src/controller/reportController.js
  src/middleware/postMiddleware.js
  src/middleware/reportMiddleware.js
  src/router/postRouter.js
  src/schema/post.js
  src/schema/report.js
Labels: :sparkles: Feature

#129 feat(#88): User 이메일 관련 API 작성
  package-lock.json
  package.json
  src/config/email.js
  src/config/responseStatus.js
  src/controller/authController.js
  src/router/authRouter.js
Labels: :sparkles: Feature

#134 Feature/110
  src/config/socket.js
  src/controller/authController.js
  src/controller/bloodController.js
  src/middleware/authMiddleware.js
  src/middleware/jwtMiddleware.js
  src/router/bloodRouter.js
Labels: :sparkles: Feature

#133 feature(#132) 추천 게시글 기능 추가, 댓글 조회 기능 수정
  src/controller/commentController.js
  src/controller/postController.js
  src/controller/reportController.js
  src/middleware/postMiddleware.js
  src/router/postRouter.js
Labels: :bug: Bug, :sparkles: Feature

#136 feat(#88) : 이메일 인증 번호 API 작성
  src/controller/authController.js
Labels: :sparkles: Feature

#137 feat(#109): 크루 생성 API 작성
  src/controller/crewController.js
  src/schema/crew.js
Labels: :sparkles: Feature

#139 feat(#138) : Notice API 작성
  index.js
  src/controller/noticeController.js
  src/router/noticeRouter.js
Labels: :sparkles: Feature

#140 Feature/95
  package-lock.json
  package.json
  src/config/responseStatus.js
  src/controller/authController.js
  src/controller/bloodController.js
  src/controller/chatRoomController.js
  src/router/authRouter.js
  src/schema/user.js
  src/view/payment.ejs
Labels: :sparkles: Feature

#141 Develop
  index.js
  package-lock.json
  package.json
  src/config/email.js
  src/config/responseStatus.js
  src/config/socket.js
  src/controller/authController.js
  src/controller/bloodController.js
  src/controller/chatRoomController.js
  src/controller/commentController.js
  src/controller/crewController.js
  src/controller/noticeController.js
  src/controller/postController.js
  src/controller/reportController.js
  src/middleware/authMiddleware.js
  src/middleware/jwtMiddleware.js
  src/middleware/postMiddleware.js
  src/router/authRouter.js
  src/router/bloodRouter.js
  src/router/noticeRouter.js
  src/router/postRouter.js
  src/schema/crew.js
  src/schema/user.js
  src/view/payment.ejs
Labels: :sparkles: Feature

#135 feat(#103): 헌혈 증서 이미지 텍스트 추출 API 작성
  package-lock.json
  package.json
  src/controller/historyController.js
  src/router/historyRouter.js
Labels: :sparkles: Feature

#142 Develop
  package-lock.json
  package.json
  src/controller/historyController.js
  src/router/historyRouter.js
Labels: :sparkles: Feature

#144 bug(#143) : Google Cloud Vision Key 생성 추가
  .github/workflows/prod_deploy.yml
Labels: :bug: Bug

#155 Develop
  src/config/redis.js
  src/middleware/jwtMiddleware.js
Labels: :bug: Bug

#156 bug(#143) : elastic cache redis 연결 오류 해결
  .ebextensions/01-connect-redis.config
  src/config/redis.js
Labels: :bug: Bug

#157 Develop
  .ebextensions/01-connect-redis.config
  src/config/redis.js
Labels: :bug: Bug

#159 bug(#158) : Crew 등록 API 오류 수정
  src/controller/crewController.js
Labels: :bug: Bug

#160 Develop
  src/controller/crewController.js
Labels: :bug: Bug

#161 feature(#103) : History API 작성
  src/controller/historyController.js
  src/router/historyRouter.js
Labels: :sparkles: Feature

#162 Develop
  src/controller/historyController.js
  src/router/historyRouter.js
Labels: :sparkles: Feature

#163 feature(#103) : History API 작성
  src/controller/historyController.js
  src/router/historyRouter.js
Labels: :bug: Bug, :sparkles: Feature

#164 Develop
  src/controller/historyController.js
  src/router/historyRouter.js
Labels: :bug: Bug, :sparkles: Feature

#166 bug(#143): Google Cloud Vision 인증 오류 수정
  src/config/responseStatus.js
  src/controller/historyController.js
Labels: :bug: Bug, :sparkles: Feature

#168 feature(#165) 게시판 전체 페이지 추가, 게시글 조회의 좋아요 여부 확인
  src/controller/postController.js
Labels: :bug: Bug, :sparkles: Feature

#169 feat(#103): History API 작성
  src/controller/historyController.js
  src/router/historyRouter.js
Labels: :sparkles: Feature

#170 Develop
  src/controller/historyController.js
  src/controller/postController.js
  src/router/historyRouter.js
Labels: :sparkles: Feature

#171 Feature/165 조회수 증가 수정
  src/controller/postController.js
Labels: :bug: Bug

#172 Develop
  README.md
  src/controller/postController.js
Labels: :page_facing_up: Docs

#173 feat(#88): User API 작성
  src/controller/authController.js
  src/router/authRouter.js
Labels: :sparkles: Feature

#174 Develop
  src/controller/authController.js
  src/router/authRouter.js
Labels: :sparkles: Feature

#175 feat(#88): User API 작성
  src/controller/authController.js
  src/router/authRouter.js
Labels: :sparkles: Feature

#176 Develop
  src/controller/authController.js
  src/router/authRouter.js
Labels: :sparkles: Feature

#177 feat(#88): User API 작성
  src/controller/authController.js
  src/router/authRouter.js
Labels: :sparkles: Feature

#178 Develop
  src/controller/authController.js
  src/router/authRouter.js
Labels: :sparkles: Feature

#181 Develop
  src/controller/bloodController.js
Labels: :bug: Bug

#183 feature(#182) : 홈화면 크루 랭킹 조회 추가
  src/controller/crewController.js
  src/router/crewRouter.js
Labels: :sparkles: Feature

#184 Develop
  src/controller/crewController.js
  src/router/crewRouter.js
Labels: :sparkles: Feature
